update

diff --git a/.github/actions/mvn-build/action.yml b/.github/actions/mvn-build/action.yml
--- a/.github/actions/mvn-build/action.yml
+++ b/.github/actions/mvn-build/action.yml
@@ -84,6 +84,43 @@ runs:
         # Export ke environment
         echo "MVN_VERSION=$MVN_VERSION" >> $GITHUB_ENV
         echo "MVN_VERSION=$MVN_VERSION" >> $GITHUB_OUTPUT
+
+        # =====================================================================================================
+        # Dipakai untuk get version consumed package
+        # =====================================================================================================
+
+        if [[ -n "${CONSUMED_PACKAGE}" ]]; then
+          for PACKAGE in ${CONSUMED_PACKAGE//,/ }; do
+            RESPONSE=$(curl -s -w "\n%{http_code}" \
+              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
+              -H "Accept: application/vnd.github+json" \
+              "https://api.github.com/orgs/${REPO_OWNER}/packages/maven/${PACKAGE}/versions")
+            
+            HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
+            BODY=$(echo "$RESPONSE" | sed '$d')
+
+            echo "HTTP Code for $PACKAGE: $HTTP_CODE"
+            echo "Response Body for $PACKAGE: $BODY"
+
+            if [[ "$HTTP_CODE" == "404" ]] || echo "$BODY" | grep -q "Package not found"; then
+              echo "⚠️ Package ${PACKAGE} not found in org ${REPO_OWNER}. Using default version 1.0.0."
+              LATEST_VERSION="1.0.0"
+            else
+              if [[ "$ENV_SERVER" == "development" || "$ENV_SERVER" == "staging" ]]; then
+                LATEST_VERSION=$(echo "$BODY" | grep -m1 '"name":' | sed -E 's/.*"name": *"([^"]+)".*/\1/')
+                echo "✅ Latest version found for $PACKAGE: $LATEST_VERSION"
+              elif [[ "$ENV_SERVER" == "production" ]]; then
+                LATEST_VERSION=$(echo "$BODY" | grep '"name":' | sed -E 's/.*"name": *"([^"]+)".*/\1/' | grep -v 'SNAPSHOT' | sort -V | tail -n1)
+                echo "✅ Latest production version found for $PACKAGE: $LATEST_VERSION"
+              fi
+            fi
+
+            echo "${PACKAGE} version=$LATEST_VERSION"
+
+            echo "$PACKAGE_version=$LATEST_VERSION" >> $GITHUB_ENV
+            echo "$PACKAGE_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
+          done
+        fi      
       env:
         GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
         REPO_OWNER: ${{ inputs.REPO_OWNER }}
